[build]
  command = "npm run netlify-build"
  publish = "dist"
  functions = "netlify/functions"
  environment = { NODE_VERSION = "18" }

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/package.json"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200 